name=IoTHubPro
version=1.0.0
author=Muhamad Fadli <fadli@iothub.local>
maintainer=Muhamad Fadli <fadli@iothub.local>
sentence=Universal & Industrial IoT Arduino Library for ESP32 and ESP8266.
paragraph=Connect ESP32/ESP8266 to the IoT Hub Pro platform seamlessly using Virtual Pins, supporting Gauges, Line Charts, SCADA HMI, GPS Maps, Sliders, Relays, and Liquid Tanks.
category=Communication
url=https://github.com/fadli1008/IOT_HUB_PRO
architectures=esp32,esp8266
includes=IoTHubPro.h
depends=PubSubClient,ArduinoJson
